[build]
  publish = "build"
  command = "npm install && cross-env CI=false npm run build"

[build.environment]
  CI = "false"
  REACT_APP_API_URL = "https://civitrack.onrender.com/api"
  REACT_APP_DEFAULT_THEME = "dark"
  NETLIFY_SITE_ID = "c909a45e-8c85-44b6-b333-7714c007caed"
  NETLIFY_ACCESS_TOKEN = "nfp_MSTSyHmHsuBQxWn9kVVztujaeoEd6mJEbecd"

# API proxy redirect
[[redirects]]
  from = "/api/*"
  to = "https://civitrack.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400"}

# Handle OPTIONS preflight requests for CORS
[[redirects]]
  from = "/api/*"
  to = "https://civitrack.onrender.com/api/:splat"
  status = 200
  force = true
  conditions = {Method = ["OPTIONS"]}
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400"}

# Specific SPA redirects for known routes
[[redirects]]
  from = "/issues/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/profile/*"
  to = "/index.html"
  status = 200

# Catch-all SPA redirect (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200