[build]
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  CI = "false"
  REACT_APP_API_URL = "https://backend-tau-inky-24.vercel.app/api"

# API proxy redirect
[[redirects]]
  from = "/api/*"
  to = "https://backend-tau-inky-24.vercel.app/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Specific SPA redirects for known routes
[[redirects]]
  from = "/issues/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/profile/*"
  to = "/index.html"
  status = 200

# Catch-all SPA redirect (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200