[build]
  base = "frontend"
  command = "npm ci && CI=false npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://backend-tau-inky-24.vercel.app/api"
  REACT_APP_SOCKET_URL = "https://backend-tau-inky-24.vercel.app"

# Specific SPA redirects for known routes
[[redirects]]
  from = "/issues/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/profile/*"
  to = "/index.html"
  status = 200

# Catch-all SPA redirect (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200