services:
  - type: web
    name: civitrack-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://civitrack-dev.netlify.app
    healthCheckPath: /
    autoDeploy: true